version: "3.7"
services:
  database:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - ./src/database/data:/var/lib/postgresql/data
      - ./docker/database/initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_SCHEMA: ${DB_SCHEMA}
    ports:
      - 15432:5432
    container_name: app-database

 
